### ISSUE TITLE
Error while running in Xcode invalid OAuth Key

### ISSUE THREAD

**Issue by abhijeetalase** [cloudsight/taptapsee-ios#1]
"error":"Invalid OAuth consumer key" this error is coming up every time i run this ..please help

**Comment by bfolkens** [comment]
Make sure to replace the api key and secret in `taptapsee-ios/TapTapSee/Config.h` with your own.

**Comment by AkkiShelke** [comment]
Sir 
    Can you please provide valid keys

**Comment by AkkiShelke** [comment]
Sir , 
       I used both new keys but still it show that error , Can you please provide me valid key ,it is for my college project and urgent,.

**Comment by ghost** [comment]
You can sign up on http://cloudsight.ai for keys.  We do offer an academic incentive as well - you can get that through contact@cloudsight.ai
