### ISSUE TITLE
"Picture in Progress" When No Photo Has Been Taken

### ISSUE THREAD

**Issue by juliagallagher** [cloudsight/taptapsee-ios#5]
From User:
_When I take a picture on tap tap see, it says it's already processing 3 images: "I can only handle
3 images at a time" is a message I hear. But, I have not taken any pictures & I had instead only launched the app then._

Version:3.1.0
System:ONE A2003
Locale:en_US
Network:No Connection

sent from my iPhone

**Comment by cweilemann** [comment]
Closing legacy issue.
